services:
  # Laravel Backend
  backend:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: laravel-backend
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - mariadb
      - redis

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - backend

  # Vue.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/node/Dockerfile
    container_name: vue-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

  # MySQL Database
  mariadb:
    image: mariadb:10.11
    container_name: laravel-mariadb
    environment:
      MARIADB_DATABASE: laravel_db
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: laravel_user
      MARIADB_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: laravel-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge
